services:

  stonehenge:
    image: "druidfi/stonehenge:4.0"
    container_name: "stonehenge"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: |-
      --providers.docker.network="${PREFIX}-network"
    labels:
      traefik.enable: "true"
    environment:
      MAILHOG_HOST: "mailhog.${DOCKER_DOMAIN}"
      TRAEFIK_HOST: "traefik.${DOCKER_DOMAIN}"
    ports:
      - "443:443"
      - "80:80"
      - "1025:1025"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/ssl # mkcert certs
      - ./traefik/dynamic:/configuration

  ssh-agent:
    image: "druidfi/ssh-agent:${SSH_IMAGE_VERSION}"
    container_name: "${PREFIX}-ssh-agent"
    restart: unless-stopped
    volumes:
      - ~/.ssh:/ssh
      - ssh:/tmp/druid_ssh-agent/

networks:
  default:
    name: "${PREFIX}-network"
    external: true

volumes:
  ssh:
    name: "${PREFIX}-ssh"
    external: true
